import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL??'http://localhost:3000';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('These mutating checks only run against the local test database.');
const anonymous=await fetch(base+'/api/monitoring');assert.equal(anonymous.status,401);
const signIn=await fetch(base+'/api/session',{method:'POST',headers:{origin:base}});assert.equal(signIn.status,201);
const cookie=signIn.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie,'Public entry must provide an isolated session');
async function api(path,body,extra={}){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{cookie,origin:base,...(body===undefined?{}:{'Content-Type':'application/json'}),...extra},body:body===undefined?undefined:JSON.stringify(body)});const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data={error:raw};}return {status:response.status,data};}
let snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.patients.length,12);assert.equal((await api('/api/health')).status,200);
async function act(action,expected=200,source='simulation',version=snapshot.version){const r=await api('/api/monitoring',{source,version,action});assert.equal(r.status,expected,JSON.stringify(r.data));if(r.status===200)snapshot=r.data;return r;}
await act({type:'login',role:'Administrator'},400);
await act({type:'prefs',value:{role:'Administrator'}},400);
await act({type:'sensor',id:'P001',module:'esp32_1',key:'bottle_level',value:-1},400);
assert.equal((await api('/api/monitoring',{source:'simulation',version:snapshot.version,action:{type:'reset'}},{origin:'https://untrusted.test'})).status,403);
await act({type:'scenario',id:'P001',name:'Critical IV-site warning'});
const critical=snapshot.state.alerts.find(a=>a.patientId==='P001'&&a.key==='critical'&&!a.resolved);assert.ok(critical);
await act({type:'ack',id:critical.id});
await act({type:'care',id:critical.id,action:'Site assessed',recover:false});
assert.equal(snapshot.state.alerts.find(a=>a.id===critical.id).resolved,false);
await act({type:'assist',id:critical.id,recover:true});
assert.equal(snapshot.state.alerts.filter(a=>a.patientId==='P001'&&!a.resolved).length,0);
snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.alerts.find(a=>a.id===critical.id).resolved,true);
assert.ok(snapshot.state.alerts.find(a=>a.id===critical.id).actions.length>=2);
const version=snapshot.version;
const competing=await Promise.all(['Concurrent A','Concurrent B'].map(text=>api('/api/monitoring',{source:'simulation',version,action:{type:'note',id:'P001',text}})));
assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);
snapshot=(await api('/api/monitoring')).data;
const notes=snapshot.state.events.filter(e=>e.message==='Concurrent A'||e.message==='Concurrent B');
assert.ok(notes.length); // Transaction loser must not leak its note.
const winner=competing.find(r=>r.status===200).data.state.events.at(-1).id;
assert.ok(notes.some(e=>e.id===winner));
await act({type:'note',id:'P001',text:'Must not save from stale version'},409,'simulation',version);
snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.events.some(e=>e.message==='Must not save from stale version'),false);
const live=await api('/api/monitoring?source=live');assert.equal(live.status,403);
await act({type:'scenario',id:'P001',name:'Normal patient'},403,'live',0);
assert.equal((await api('/api/device-key',{action:'rotate'})).status,403);
assert.equal((await api('/api/telemetry',{})).status,403);
const second=await fetch(base+'/api/session',{method:'POST',headers:{origin:base}});
assert.equal(second.status,201);
const secondCookie=second.headers.get('set-cookie')?.split(';')[0];assert.ok(secondCookie);assert.notEqual(secondCookie,cookie);
const other=(await api('/api/monitoring',undefined,{cookie:secondCookie})).data;
assert.equal(other.state.events.some(e=>e.id===winner),false);
assert.equal(other.state.alerts.some(a=>a.id===critical.id),false);
assert.equal((await api('/api/monitoring',{source:'simulation',version:other.version,action:{type:'ack',id:critical.id}},{cookie:secondCookie})).status,404);
const forgery=await fetch(base+'/api/monitoring',{headers:{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'forged@example.com'}});assert.equal(forgery.status,401);
const reuse=await api('/api/session',{});assert.equal(reuse.status,200);
snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.alerts.find(a=>a.id===critical.id).resolved,true);
await act({type:'handover',text:'Saved public sample handover'});await act({type:'complete'});
assert.ok((await api('/api/monitoring')).data.state.handover.previous.includes('Saved public sample handover'));
const end=await fetch(base+'/api/session',{method:'DELETE',headers:{cookie,origin:base}});assert.equal(end.status,200);
assert.equal((await api('/api/monitoring')).status,401);
assert.equal((await api('/api/monitoring',undefined,{cookie:secondCookie})).status,200);
console.log('PASS: public sessions, origin protection, validation, PostgreSQL recovery persistence, concurrent writes, stale-action rejection, visitor isolation, handover, live-data restrictions, header-spoof rejection and logout.');
