import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL??'http://localhost:5173';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('These mutating checks only run against the local test database.');
const anonymous=await fetch(base+'/api/monitoring');assert.equal(anonymous.status,401);
const signIn=await fetch(base+'/signin-with-chatgpt?return_to=%2F',{redirect:'manual'});
const cookie=signIn.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie,'Local mock sign-in must provide a session');
async function api(path,body,extra={}){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{cookie,origin:base,...(body===undefined?{}:{'Content-Type':'application/json'}),...extra},body:body===undefined?undefined:JSON.stringify(body)});const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data={error:raw};}return {status:response.status,data};}
let snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.patients.length,12);assert.equal((await api('/api/health')).status,200);
async function act(action,expected=200,source='simulation',version=snapshot.version){const r=await api('/api/monitoring',{source,version,action});assert.equal(r.status,expected,JSON.stringify(r.data));if(r.status===200)snapshot=r.data;return r;}
await act({type:'login',role:'Administrator'},400);
await act({type:'prefs',value:{role:'Administrator'}},400);
await act({type:'sensor',id:'P001',module:'esp32_1',key:'bottle_level',value:-1},400);
assert.equal((await api('/api/monitoring',{source:'simulation',version:snapshot.version,action:{type:'reset'}},{origin:'https://untrusted.test'})).status,403);
await act({type:'scenario',id:'P001',name:'Critical IV-site warning'});
const critical=snapshot.state.alerts.find(a=>a.patientId==='P001'&&a.key==='critical'&&!a.resolved);assert.ok(critical);
await act({type:'ack',id:critical.id});
await act({type:'care',id:critical.id,action:'Site assessed',recover:false});
assert.equal(snapshot.state.alerts.find(a=>a.id===critical.id).resolved,false);
await act({type:'assist',id:critical.id,recover:true});
assert.equal(snapshot.state.alerts.filter(a=>a.patientId==='P001'&&!a.resolved).length,0);
snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.alerts.find(a=>a.id===critical.id).resolved,true);
assert.ok(snapshot.state.alerts.find(a=>a.id===critical.id).actions.length>=2);
const version=snapshot.version;
const competing=await Promise.all(['Concurrent A','Concurrent B'].map(text=>api('/api/monitoring',{source:'simulation',version,action:{type:'note',id:'P001',text}})));
assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);
snapshot=(await api('/api/monitoring')).data;
const notes=snapshot.state.events.filter(e=>e.message==='Concurrent A'||e.message==='Concurrent B');
assert.ok(notes.length); // Transaction loser must not leak its note.
const winner=competing.find(r=>r.status===200).data.state.events.at(-1).id;
assert.ok(notes.some(e=>e.id===winner));
await act({type:'note',id:'P001',text:'Must not save from stale version'},409,'simulation',version);
snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.events.some(e=>e.message==='Must not save from stale version'),false);
const saved=snapshot.state.alerts.find(a=>a.id===critical.id);
const live=await api('/api/monitoring?source=live');
await act({type:'scenario',id:'P001',name:'Normal patient'},403,'live',live.data.version);
const key=await api('/api/device-key',{action:'rotate'});assert.equal(key.status,200);
const now=Date.now(),packet={patient:{id:'TEST-DEVICE',name:'Fictional API patient',bed:'TEST',ward:'API tests'},esp32_1:{connected:true,bottle_level:80,pressure:35,drop_count:10,drop_rate:20,air_bubble:false,last_received:now},esp32_2:{connected:true,moisture:20,strain:20,last_received:now},gateway:{esp_now:true,wifi:true,node_red:true}};
assert.equal((await api('/api/telemetry',packet,{authorization:'Bearer '+key.data.token})).status,202);
const liveAfter=(await api('/api/monitoring?source=live')).data;
assert.equal(liveAfter.state.patients.find(p=>p.patient.id==='TEST-DEVICE').esp32_1.bottle_level,80);
packet.esp32_1.last_received=now-1000;
assert.equal((await api('/api/telemetry',packet,{authorization:'Bearer '+key.data.token})).status,409);
await api('/api/device-key',{action:'revoke'});
assert.equal((await api('/api/telemetry',packet,{authorization:'Bearer '+key.data.token})).status,401);
snapshot=(await api('/api/monitoring')).data;
assert.equal(snapshot.state.patients.some(p=>p.patient.id==='TEST-DEVICE'),false);
assert.equal(snapshot.state.alerts.find(a=>a.id===saved.id).resolved,true);
console.log('PASS: authentication, origin protection, validation, database recovery persistence, concurrent writes, stale-action rejection, source isolation, telemetry ingestion and key revocation.');
