'use client';
import {useEffect,useState} from 'react';
import {Database,ShieldCheck} from 'lucide-react';
export function DatabasePanel(){
 const [health,setHealth]=useState<any>(null),[error,setError]=useState(''),[key,setKey]=useState(''),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let stopped=false;Promise.all([fetch('/api/health',{cache:'no-store'}),fetch('/api/device-key',{cache:'no-store'})]).then(async([h,k])=>{if(!h.ok||!k.ok)throw new Error('Unable to verify backend status.');const a=await h.json(),b=await k.json() as any;if(!stopped){setHealth(a);setConfigured(b.configured);}}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;};},[]);
 const keyAction=async(action:'rotate'|'revoke')=>{setBusy(true);setError('');setKey('');try{const response=await fetch('/api/device-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const data=await response.json() as any;if(!response.ok)throw new Error(data.error);setConfigured(data.configured);setKey(data.token??'');}catch(e){setError(e instanceof Error?e.message:'Unable to update key.');}finally{setBusy(false);}};
 return <section className="panel database-panel"><div className="section-heading"><h2><Database size={20}/> Connected application</h2><span className="status normal"><ShieldCheck size={14}/>{health?'Database connected':'Checking connection'}</span></div><p>Patient records, alerts, actions, preferences and handovers are saved in your private database workspace.</p><div className="database-service-grid"><div><small>Frontend</small><b>TISSENSE web application</b></div><div><small>Backend</small><b>{health?.backend??'Checking...'}</b></div><div><small>Database</small><b>{health?.database??'Checking...'}</b></div></div>{error&&<p role="alert" className="form-error">{error}</p>}<details><summary>Device ingestion API</summary><p>Endpoint: <code>/api/telemetry</code>. Real devices are not configured. The private site's access controls also apply; your gateway must have approved access before sending data.</p><p>Use a complete patient packet and an <code>Authorization: Bearer</code> key. Keys only permit telemetry ingestion into your live workspace.</p><div className="button-row"><button className="secondary-button" disabled={busy} onClick={()=>keyAction('rotate')}>{configured?'Replace ingestion key':'Create ingestion key'}</button>{configured&&<button className="secondary-button" disabled={busy} onClick={()=>keyAction('revoke')}>Revoke key</button>}</div>{key&&<label className="field-label">Save this key securely; it is shown once. Creating another key revokes it.<input className="text-input" aria-label="New ingestion key" readOnly value={key}/></label>}</details></section>;
}
