export const THRESHOLDS = Object.freeze({ bottle:15, pressure:85, moistureWarning:50, moistureCritical:70, strainWarning:50, strainCritical:60 });
export type Status = 'critical'|'warning'|'normal'|'offline';
export type Patient = { patient:{id:string;name:string;bed:string;room:string;ward:string;nurse:string;started:number}; esp32_1:{connected:boolean;bottle_level:number|null;drop_count:number|null;drop_rate:number|null;pressure:number|null;air_bubble:boolean|null;last_received:number};esp32_2:{connected:boolean;moisture:number|null;strain:number|null;last_received:number};gateway:{esp_now:boolean;wifi:boolean;node_red:boolean};system:{mode:'simulation'|'live';timestamp:number};drops:number[];invalid:string[] };
export type Alert = { id:string;patientId:string;bed:string;source:string;parameter:string;currentValue:string;threshold:string;message:string;severity:Status;createdAt:number;acknowledged:boolean;acknowledgedBy?:string;acknowledgedAt?:number;resolved:boolean;resolvedAt?:number;key:string;lastObserved:number };
export type Event = {id:string;patientId:string;message:string;at:number;kind:string;nurse?:string};
export type Notification = {id:string;patientId:string;message:string;at:number;group:string;read:boolean};
export const valid=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=100;
export const getBottleStatus=(n:number|null)=>n===null?'offline':n<=THRESHOLDS.bottle?'warning':'normal';
export const getPressureStatus=(n:number|null)=>n===null?'offline':n>THRESHOLDS.pressure?'warning':'normal';
export const getAirBubbleStatus=(v:boolean|null)=>v===null?'offline':v?'warning':'normal';
export const getIVSiteStatus=(m:number|null,s:number|null):Status=>m!==null&&s!==null&&m>=THRESHOLDS.moistureCritical&&s>=THRESHOLDS.strainCritical?'critical':(m!==null&&m>=THRESHOLDS.moistureWarning)||(s!==null&&s>=THRESHOLDS.strainWarning)?'warning':m===null||s===null?'offline':'normal';
export const getESP32TwoStatus=(p:Patient)=>getIVSiteStatus(p.esp32_2.moisture,p.esp32_2.strain);
export const getESP32OneStatus=(p:Patient):Status=>[getBottleStatus(p.esp32_1.bottle_level),getPressureStatus(p.esp32_1.pressure),getAirBubbleStatus(p.esp32_1.air_bubble)].includes('warning')?'warning':'normal';
export function freshness(p:Patient,module:1|2,now=Date.now()){const n=module===1?p.esp32_1:p.esp32_2;return !n.connected||!p.gateway.node_red||!p.gateway.wifi||(module===1&&!p.gateway.esp_now)||now-n.last_received>60000?'unavailable':now-n.last_received>15000?'delayed':'current';}
export function getOverallStatus(p:Patient,now=Date.now()):Status{const a=freshness(p,1,now)==='current'?getESP32OneStatus(p):'offline';const b=freshness(p,2,now)==='current'?getESP32TwoStatus(p):'offline';if(b==='critical')return 'critical';if(a==='warning'||b==='warning')return 'warning';return a==='offline'||b==='offline'||p.invalid.length>0?'offline':'normal';}
export function getMonitoringInsight(p:Patient,now=Date.now()){const s=getOverallStatus(p,now);if(s==='critical')return 'Moisture and strain exceed configured critical thresholds. Immediate nurse assessment recommended.';if(freshness(p,1,now)!=='current'||freshness(p,2,now)!=='current')return 'Monitoring data is delayed or unavailable. Verify device connectivity.';if(p.invalid.length)return 'Sensor data invalid. Verify the sensor and incoming payload.';if(p.esp32_1.air_bubble)return 'Air bubble detected. Check patient and IV line.';if(getBottleStatus(p.esp32_1.bottle_level)==='warning')return 'Bottle level is low. Nurse assessment recommended.';if(getPressureStatus(p.esp32_1.pressure)==='warning')return 'Tube pressure exceeds the configured threshold. Nurse assessment recommended.';if((p.esp32_2.moisture??0)>=50)return 'Elevated IV-site moisture. Possible fluid leakage warning; nurse assessment recommended.';if((p.esp32_2.strain??0)>=50)return 'Elevated IV-site strain. Possible swelling warning; nurse assessment recommended.';return 'IV monitoring values are currently within configured limits.';}
export function getActiveAlerts(p:Patient,now=Date.now()){
 const out:Omit<Alert,'id'|'createdAt'|'acknowledged'|'resolved'|'lastObserved'>[]=[];
 const add=(key:string,source:string,parameter:string,currentValue:string,threshold:string,message:string,severity:Status='warning')=>out.push({key,patientId:p.patient.id,bed:p.patient.bed,source,parameter,currentValue,threshold,message,severity});
 if(freshness(p,1,now)==='current') {const a=p.esp32_1;if(getBottleStatus(a.bottle_level)==='warning')add('bottle','ESP32 #1','Bottle level',`${a.bottle_level}%`,'≤ 15%','Low bottle level');if(getPressureStatus(a.pressure)==='warning')add('pressure','ESP32 #1','Tube pressure',`${a.pressure}%`,'> 85%','High pressure');if(a.air_bubble)add('air','ESP32 #1','Air bubble','Detected','Detected = true','Air bubble detected');}
 if(freshness(p,2,now)==='current') {const b=p.esp32_2;if(getIVSiteStatus(b.moisture,b.strain)==='critical')add('critical','ESP32 #2','Moisture + strain',`${b.moisture}% / ${b.strain}%`,'≥ 70% and ≥ 60%','Possible IV-site early-warning condition','critical');if(b.moisture!==null&&b.moisture>=50)add('moisture','ESP32 #2','Moisture',`${b.moisture}%`,'≥ 50%','Possible fluid leakage warning');if(b.strain!==null&&b.strain>=50)add('strain','ESP32 #2','Strain',`${b.strain}%`,'≥ 50%','Possible swelling warning');}
 for(const module of [1,2] as const){const f=freshness(p,module,now);if(f!=='current')add(`device${module}`,`ESP32 #${module}`,'Connectivity',f,'15 s delayed / 60 s unavailable',`ESP32 #${module}: ${f==='delayed'?'data delayed':'monitoring data unavailable'}`,'offline');}
 if(!p.gateway.node_red)add('node','Gateway','Node-RED','Disconnected','Connected','Node-RED disconnected','offline');
 if(p.invalid.length)add('invalid','Sensor','Validation',p.invalid.join(', '),'Valid sensor payload','Sensor data invalid','offline');return out;
}
export function reconcileAlerts(previous:Alert[],patients:Patient[],now=Date.now()):Alert[]{let result=previous.map(a=>({...a}));for(const p of patients){const current=getActiveAlerts(p,now);for(const a of result.filter(a=>a.patientId===p.patient.id&&!a.resolved)){const match=current.find(x=>x.key===a.key);if(match){a.currentValue=match.currentValue;a.message=match.message;a.lastObserved=now;}else {const module=a.source==='ESP32 #1'?1:a.source==='ESP32 #2'?2:null;const missing=module&&(freshness(p,module,now)!=='current'||p.invalid.length>0);if(!missing){a.resolved=true;a.resolvedAt=now;}}}for(const c of current)if(!result.some(a=>a.patientId===c.patientId&&a.key===c.key&&!a.resolved))result.push({...c,id:`${c.patientId}-${c.key}-${now}`,createdAt:now,acknowledged:false,resolved:false,lastObserved:now});}return result;}
export const priority={critical:0,warning:1,normal:2,offline:3};
export function sortPatients(ps:Patient[],alerts:Alert[],now=Date.now()){const latest=(p:Patient)=>Math.max(0,...alerts.filter(a=>a.patientId===p.patient.id&&!a.resolved).map(a=>a.createdAt));return [...ps].sort((a,b)=>priority[getOverallStatus(a,now)]-priority[getOverallStatus(b,now)]||latest(b)-latest(a)||a.patient.bed.localeCompare(b.patient.bed));}
export function normalizePayload(raw:any,mode:'simulation'|'live'='live',now=Date.now()):Patient {if(!raw?.patient?.id||!raw.patient.name||!raw.patient.bed)throw new Error('Patient ID, name and bed are required.');const invalid:string[]=[];const pct=(v:unknown,k:string)=>{if(!valid(v)){invalid.push(k);return null;}return v;};const num=(v:unknown,k:string)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0){invalid.push(k);return null;}return v;};const bool=(v:unknown,k:string)=>{if(typeof v!=='boolean'){invalid.push(k);return null;}return v;};const ts=(v:unknown)=>{const n=typeof v==='number'?v:typeof v==='string'?Date.parse(v):NaN;return Number.isFinite(n)&&n<=now+5000?n:0;};const a=raw.esp32_1??{},b=raw.esp32_2??{},g=raw.gateway??{};return {patient:{id:String(raw.patient.id),name:String(raw.patient.name),bed:String(raw.patient.bed),room:String(raw.patient.room??'—'),ward:String(raw.patient.ward??'Unassigned'),nurse:String(raw.patient.nurse??'Unassigned'),started:raw.patient.started??now},esp32_1:{connected:a.connected===true,bottle_level:pct(a.bottle_level,'Bottle level'),pressure:pct(a.pressure,'Pressure'),drop_count:num(a.drop_count,'Drop count'),drop_rate:num(a.drop_rate,'Drop rate'),air_bubble:bool(a.air_bubble,'Air bubble'),last_received:ts(a.last_received)},esp32_2:{connected:b.connected===true,moisture:pct(b.moisture,'Moisture'),strain:pct(b.strain,'Strain'),last_received:ts(b.last_received)},gateway:{esp_now:g.esp_now===true,wifi:g.wifi===true,node_red:g.node_red===true},system:{mode,timestamp:now},drops:[],invalid};}
export function seedPatients(now=Date.now()):Patient[]{const names=['Lakshmi Narayan','Vijay Krishnan','Anita Sharma','Suresh Menon','Divya Rajan','Karthik S','Fathima Ali','Arun Kumar','Sneha R','Ravi Chandran','Meena S','Rahul Prakash'];return names.map((name,i)=>{const bed=String(i+1).padStart(2,'0');const rate=18+i%7;return {patient:{id:`P0${bed}`,name,bed,room:String(201+Math.floor(i/3)),ward:'Ward A',nurse:i===5||i===8?'Nurse Ananya':'Nurse Priya',started:now-3600000*(1+i%4)},esp32_1:{connected:true,bottle_level:i===10?14:68-i*2,drop_count:146+i*17,drop_rate:rate,pressure:32+i,air_bubble:false,last_received:now},esp32_2:{connected:true,moisture:i===11?76:i===2?58:20+i,strain:i===11?64:18+i,last_received:now},gateway:{esp_now:true,wifi:true,node_red:true},system:{mode:'simulation',timestamp:now},drops:Array.from({length:rate},(_,j)=>now-j*60000/rate),invalid:[]};});}
export const scenarios=['Normal patient','Low bottle','High pressure','Air bubble','Possible fluid leakage warning','Possible swelling warning','Critical IV-site warning','ESP32 #1 offline','ESP32 #2 offline','Node-RED disconnected'];
export function applyScenario(p:Patient,name:string,now=Date.now()):Patient {const q=structuredClone(p);Object.assign(q.esp32_1,{connected:true,bottle_level:75,pressure:35,air_bubble:false,last_received:now});Object.assign(q.esp32_2,{connected:true,moisture:25,strain:20,last_received:now});q.gateway={esp_now:true,wifi:true,node_red:true};q.invalid=[];if(name===scenarios[1])q.esp32_1.bottle_level=12;if(name===scenarios[2])q.esp32_1.pressure=90;if(name===scenarios[3])q.esp32_1.air_bubble=true;if(name===scenarios[4])q.esp32_2.moisture=58;if(name===scenarios[5])q.esp32_2.strain=55;if(name===scenarios[6])Object.assign(q.esp32_2,{moisture:75,strain:65});if(name===scenarios[7])q.esp32_1.connected=false;if(name===scenarios[8])q.esp32_2.connected=false;if(name===scenarios[9])q.gateway.node_red=false;return q;}
export function generateDrop(p:Patient,now=Date.now()){const drops=[...p.drops.filter(t=>now-t<60000),now];return {...p,drops,esp32_1:{...p.esp32_1,drop_count:(p.esp32_1.drop_count??0)+1,drop_rate:drops.length,last_received:now}};}
